config/routes.rb
Rails.application.routes.draw do

  get 'providers/show'

  get 'users/show'

  get 'user/show'

  resources :services
  resources :categories
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'static_pages/about'
  root 'home#index'

  devise_for :users
  devise_for :providers

  get 'filter_services_by_category' => 'orders#filter_services_by_category'

  resources :users, :only => [:show]
  resources :providers, :only => [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :services
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :provider
  belongs_to :service
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :orders
  has_many :services
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
  belongs_to :provider
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base



  private

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #if user_signed_in?
    #  redirect_to static_pages_about_path, status: 301
    #else
    #  redirect_to new_user_session_path
    #end
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  private

    def order_params
      params.require(:order).permit(:user_id, :provider_id, :dateCreated, :finishDate, :cost, :address, :category_id, :service_id)
    end

  def currentDate
    @current_Time = DateTime.now
  end

  def filter_services_by_category
    @filtered_services = Service.all.where(category_id: params[:selected_category])
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def show
    @provider = Provider.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < InheritedResources::Base



  private

    def service_params
      params.require(:service).permit(:name, :description, :category_id, :provider_id, :cost)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>WELCOME to What Around Me</h1>
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.first_name %></strong>.
      <%= link_to 'Show profile', current_user %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% elsif provider_signed_in? %>
      Logged in as <strong><%= current_provider.first_name %></strong>.
      <%= link_to 'Show profile', current_provider %> |
      <%= link_to "Logout", destroy_provider_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <p>User:</p>
      <%= link_to "User: Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "User: Login", new_user_session_path, :class => 'navbar-link'  %>
      <br>
      <br>
      <p>Provider:</p>
      <%= link_to "Provider: Sign up", new_provider_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Provider: Login ", new_provider_session_path, :class => 'navbar-link'  %>
  <% end %>