config/routes.rb
Rails.application.routes.draw do

  get 'providers/show'

  get 'users/show'

  get 'user/show'

  resources :services
  resources :categories
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'static_pages/about'
  root 'home#index'

  devise_for :users
  devise_for :providers

  get 'filter_services_by_category' => 'orders#filter_services_by_category'

  resources :users, :only => [:show]
  resources :providers, :only => [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :services
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :provider
  belongs_to :service
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :orders
  has_many :services
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
  belongs_to :provider
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :birth_date, :phone_number, :id_number, :fiscal_number, :email, :password, :remember_me, :address, :job, :labor_cost) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :birth_date, :phone_number, :id_number, :fiscal_number, :email, :password, :current_password, :remember_me, :address, :job, :labor_cost) }
  end

end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base



  private

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #if user_signed_in?
    #  redirect_to static_pages_about_path, status: 301
    #else
    #  redirect_to new_user_session_path
    #end
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  private

    def order_params
      params.require(:order).permit(:user_id, :provider_id, :dateCreated, :finishDate, :cost, :address, :category_id, :service_id)
    end

  def currentDate
    @current_Time = DateTime.now
  end

  def filter_services_by_category
    @filtered_services = Service.all.where(category_id: params[:selected_category])
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def show
    @provider = Provider.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < InheritedResources::Base



  private

    def service_params
      params.require(:service).permit(:name, :description, :category_id, :provider_id, :cost)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :category_id %>
      <%= f.collection_select(:category_id, Category.all, :id, :name) %>
    </div>

    <div class="field">
      <%= f.label :service_id %>
      <%= f.collection_select(:service_id, Service.all, :id, :name) %>
    </div>

    <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

   <div class="field">
    <%= f.label :provider_id %>
    <%= f.collection_select(:provider_id, Provider.all, :id, :first_name) %>
   </div>


  <div class="field">
    <%= f.hidden_field :dateCreated, :value => Time.now, :readonly => true %>
  </div>

  <div class="field">
    <%= f.label :finishDate %>
    <%= f.date_select :finishDate %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/filter_services_by_category.js.erb
$('select#order_service_id').html('<%= j options_from_collection_for_select(@filtered_services, :id, :name) %>');

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Service</th>
      <th>User</th>
      <th>Provider</th>
      <th>Datecreated</th>
      <th>Finishdate</th>
      <th>Cost</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% if user_signed_in? %>
      <% @orders.where(user_id: current_user.id).find_each do |order| %>
          <tr>
            <td><%= order.service.name %></td>
            <td><%= order.user.email %></td>
            <td><%= order.provider.email %></td>
            <td><%= order.dateCreated %></td>
            <td><%= order.finishDate %></td>
            <td><%= order.cost %></td>
            <td><%= order.address %></td>
            <td><%= link_to 'Show', order %></td>
          </tr>
      <% end %>
  <% elsif provider_signed_in? %>
      <% @orders.where(provider_id: current_provider.id).find_each do |order| %>
          <tr>
            <td><%= order.service.name %></td>
            <td><%= order.user.email %></td>
            <td><%= order.provider.email %></td>
            <td><%= order.dateCreated %></td>
            <td><%= order.finishDate %></td>
            <td><%= order.cost %></td>
            <td><%= order.address %></td>
            <td><%= link_to 'Show', order %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>
<% if user_signed_in? %>
<%= link_to 'New Order', new_order_path %>
<% end %>

<br>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', url_for(:back) %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order.user.id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @order.provider.first_name %>
</p>

<p>
  <strong>Datecreated:</strong>
  <%= @order.dateCreated %>
</p>

<p>
  <strong>Finishdate:</strong>
  <%= @order.finishDate %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @order.cost %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<%= link_to 'Back', orders_path %>

app/views/providers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/providers/show.html.erb
<h1>Profile</h1>

<p>
  <strong>First Name:</strong>
  <%= @provider.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @provider.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @provider.email %>
</p>

<p>
  <strong>Birth Date:</strong>
  <%= @provider.birth_date %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @provider.phone_number %>
</p>

<p>
  <strong>ID Number:</strong>
  <%= @provider.id_number %>
</p>

<p>
  <strong>Fiscal Number:</strong>
  <%= @provider.fiscal_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @provider.address %>
</p>


<%= link_to 'Edit', edit_provider_registration_path, :class => 'navbar-link' %>

<%= link_to "Back", :back %>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |f| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.hidden_field :provider_id , :value => current_provider.id %>
    </div>

    <div class="field">
      <%= f.label :category_id %>
      <%= f.collection_select(:category_id, Category.all, :id, :name) %>
    </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

    <div class="field">
      <%= f.label :cost %>
      <%= f.text_field :cost %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Description</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.where(provider_id: current_provider.id).find_each do |service| %>
      <tr>
        <td><%= service.category.name %></td>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.cost %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @service.category %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>